#include "pinyinmap.h"

map<string, int32_t> initPhoneIDMap() {
    return {
        {"sil",0},
        {"eos",1},
        {"sp",2},
        {"#0",3},
        {"#1",4},
        {"#2",5},
        {"#3",6},
        {"^",7},
        {"b",8},
        {"c",9},
        {"ch",10},
        {"d",11},
        {"f",12},
        {"g",13},
        {"h",14},
        {"j",15},
        {"k",16},
        {"l",17},
        {"m",18},
        {"n",19},
        {"p",20},
        {"q",21},
        {"r",22},
        {"s",23},
        {"sh",24},
        {"t",25},
        {"x",26},
        {"z",27},
        {"zh",28},
        {"a1",29},
        {"a2",30},
        {"a3",31},
        {"a4",32},
        {"a5",33},
        {"ai1",34},
        {"ai2",35},
        {"ai3",36},
        {"ai4",37},
        {"ai5",38},
        {"an1",39},
        {"an2",40},
        {"an3",41},
        {"an4",42},
        {"an5",43},
        {"ang1",44},
        {"ang2",45},
        {"ang3",46},
        {"ang4",47},
        {"ang5",48},
        {"ao1",49},
        {"ao2",50},
        {"ao3",51},
        {"ao4",52},
        {"ao5",53},
        {"e1",54},
        {"e2",55},
        {"e3",56},
        {"e4",57},
        {"e5",58},
        {"ei1",59},
        {"ei2",60},
        {"ei3",61},
        {"ei4",62},
        {"ei5",63},
        {"en1",64},
        {"en2",65},
        {"en3",66},
        {"en4",67},
        {"en5",68},
        {"eng1",69},
        {"eng2",70},
        {"eng3",71},
        {"eng4",72},
        {"eng5",73},
        {"er1",74},
        {"er2",75},
        {"er3",76},
        {"er4",77},
        {"er5",78},
        {"i1",79},
        {"i2",80},
        {"i3",81},
        {"i4",82},
        {"i5",83},
        {"ia1",84},
        {"ia2",85},
        {"ia3",86},
        {"ia4",87},
        {"ia5",88},
        {"ian1",89},
        {"ian2",90},
        {"ian3",91},
        {"ian4",92},
        {"ian5",93},
        {"iang1",94},
        {"iang2",95},
        {"iang3",96},
        {"iang4",97},
        {"iang5",98},
        {"iao1",99},
        {"iao2",100},
        {"iao3",101},
        {"iao4",102},
        {"iao5",103},
        {"ie1",104},
        {"ie2",105},
        {"ie3",106},
        {"ie4",107},
        {"ie5",108},
        {"ii1",109},
        {"ii2",110},
        {"ii3",111},
        {"ii4",112},
        {"ii5",113},
        {"iii1",114},
        {"iii2",115},
        {"iii3",116},
        {"iii4",117},
        {"iii5",118},
        {"in1",119},
        {"in2",120},
        {"in3",121},
        {"in4",122},
        {"in5",123},
        {"ing1",124},
        {"ing2",125},
        {"ing3",126},
        {"ing4",127},
        {"ing5",128},
        {"iong1",129},
        {"iong2",130},
        {"iong3",131},
        {"iong4",132},
        {"iong5",133},
        {"iou1",134},
        {"iou2",135},
        {"iou3",136},
        {"iou4",137},
        {"iou5",138},
        {"o1",139},
        {"o2",140},
        {"o3",141},
        {"o4",142},
        {"o5",143},
        {"ong1",144},
        {"ong2",145},
        {"ong3",146},
        {"ong4",147},
        {"ong5",148},
        {"ou1",149},
        {"ou2",150},
        {"ou3",151},
        {"ou4",152},
        {"ou5",153},
        {"u1",154},
        {"u2",155},
        {"u3",156},
        {"u4",157},
        {"u5",158},
        {"ua1",159},
        {"ua2",160},
        {"ua3",161},
        {"ua4",162},
        {"ua5",163},
        {"uai1",164},
        {"uai2",165},
        {"uai3",166},
        {"uai4",167},
        {"uai5",168},
        {"uan1",169},
        {"uan2",170},
        {"uan3",171},
        {"uan4",172},
        {"uan5",173},
        {"uang1",174},
        {"uang2",175},
        {"uang3",176},
        {"uang4",177},
        {"uang5",178},
        {"uei1",179},
        {"uei2",180},
        {"uei3",181},
        {"uei4",182},
        {"uei5",183},
        {"uen1",184},
        {"uen2",185},
        {"uen3",186},
        {"uen4",187},
        {"uen5",188},
        {"ueng1",189},
        {"ueng2",190},
        {"ueng3",191},
        {"ueng4",192},
        {"ueng5",193},
        {"uo1",194},
        {"uo2",195},
        {"uo3",196},
        {"uo4",197},
        {"uo5",198},
        {"v1",199},
        {"v2",200},
        {"v3",201},
        {"v4",202},
        {"v5",203},
        {"van1",204},
        {"van2",205},
        {"van3",206},
        {"van4",207},
        {"van5",208},
        {"ve1",209},
        {"ve2",210},
        {"ve3",211},
        {"ve4",212},
        {"ve5",213},
        {"vn1",214},
        {"vn2",215},
        {"vn3",216},
        {"vn4",217},
        {"vn5",218}
    };
}

map<uint16_t, uint16_t> initNumMap() {
    return {
        {0x31,0x4e00},
        {0x32,0x4e8c},
        {0x33,0x4e09},
        {0x34,0x56db},
        {0x35,0x4e94},
        {0x36,0x516d},
        {0x37,0x4e03},
        {0x38,0x516b},
        {0x39,0x4e5d},
        {0x30,0x96f6}
    };
}


multimap<string, vector<string> > initPinyin2Phone() {
    return {
       {"a", {"^", "a"}},
       {"ai",{"^", "ai"}},
       {"ai", {"^", "ai"}},
       {"an", {"^", "an"}},
       {"ang", {"^", "ang"}},
       {"ao", {"^", "ao"}},
       {"ba", {"b", "a"}},
       {"bai", {"b", "ai"}},
       {"ban", {"b", "an"}},
       {"bang", {"b", "ang"}},
       {"bao", {"b", "ao"}},
       {"be", {"b", "e"}},
       {"bei", {"b", "ei"}},
       {"ben", {"b", "en"}},
       {"beng", {"b", "eng"}},
       {"bi", {"b", "i"}},
       {"bian", {"b", "ian"}},
       {"biao", {"b", "iao"}},
       {"bie", {"b", "ie"}},
       {"bin", {"b", "in"}},
       {"bing", {"b", "ing"}},
       {"bo", {"b", "o"}},
       {"bu", {"b", "u"}},
       {"ca", {"c", "a"}},
       {"cai", {"c", "ai"}},
       {"can", {"c", "an"}},
       {"cang", {"c", "ang"}},
       {"cao", {"c", "ao"}},
       {"ce", {"c", "e"}},
       {"cen", {"c", "en"}},
       {"ceng", {"c", "eng"}},
       {"cha", {"ch", "a"}},
       {"chai", {"ch", "ai"}},
       {"chan", {"ch", "an"}},
       {"chang", {"ch", "ang"}},
       {"chao", {"ch", "ao"}},
       {"che", {"ch", "e"}},
       {"chen", {"ch", "en"}},
       {"cheng", {"ch", "eng"}},
       {"chi", {"ch", "iii"}},
       {"chong", {"ch", "ong"}},
       {"chou", {"ch", "ou"}},
       {"chu", {"ch", "u"}},
       {"chua", {"ch", "ua"}},
       {"chuai", {"ch", "uai"}},
       {"chuan", {"ch", "uan"}},
       {"chuang", {"ch", "uang"}},
       {"chui", {"ch", "uei"}},
       {"chun", {"ch", "uen"}},
       {"chuo", {"ch", "uo"}},
       {"ci", {"c", "ii"}},
       {"cong", {"c", "ong"}},
       {"cou", {"c", "ou"}},
       {"cu", {"c", "u"}},
       {"cuan", {"c", "uan"}},
       {"cui", {"c", "uei"}},
       {"cun", {"c", "uen"}},
       {"cuo", {"c", "uo"}},
       {"da", {"d", "a"}},
       {"dai", {"d", "ai"}},
       {"dan", {"d", "an"}},
       {"dang", {"d", "ang"}},
       {"dao", {"d", "ao"}},
       {"de", {"d", "e"}},
       {"dei", {"d", "ei"}},
       {"den", {"d", "en"}},
       {"deng", {"d", "eng"}},
       {"di", {"d", "i"}},
       {"dia", {"d", "ia"}},
       {"dian", {"d", "ian"}},
       {"diao", {"d", "iao"}},
       {"die", {"d", "ie"}},
       {"ding", {"d", "ing"}},
       {"diu", {"d", "iou"}},
       {"dong", {"d", "ong"}},
       {"dou", {"d", "ou"}},
       {"du", {"d", "u"}},
       {"duan", {"d", "uan"}},
       {"dui", {"d", "uei"}},
       {"dun", {"d", "uen"}},
       {"duo", {"d", "uo"}},
       {"e", {"^", "e"}},
       {"ei", {"^", "ei"}},
       {"en", {"^", "en"}},
       {"ng", {"^", "en"}},
       {"eng", {"^", "eng"}},
       {"er", {"^", "er"}},
       {"fa", {"f", "a"}},
       {"fan", {"f", "an"}},
       {"fang", {"f", "ang"}},
       {"fei", {"f", "ei"}},
       {"fen", {"f", "en"}},
       {"feng", {"f", "eng"}},
       {"fo", {"f", "o"}},
       {"fou", {"f", "ou"}},
       {"fu", {"f", "u"}},
       {"ga", {"g", "a"}},
       {"gai", {"g", "ai"}},
       {"gan", {"g", "an"}},
       {"gang", {"g", "ang"}},
       {"gao", {"g", "ao"}},
       {"ge", {"g", "e"}},
       {"gei", {"g", "ei"}},
       {"gen", {"g", "en"}},
       {"geng", {"g", "eng"}},
       {"gong", {"g", "ong"}},
       {"gou", {"g", "ou"}},
       {"gu", {"g", "u"}},
       {"gua", {"g", "ua"}},
       {"guai", {"g", "uai"}},
       {"guan", {"g", "uan"}},
       {"guang", {"g", "uang"}},
       {"gui", {"g", "uei"}},
       {"gun", {"g", "uen"}},
       {"guo", {"g", "uo"}},
       {"ha", {"h", "a"}},
       {"hai", {"h", "ai"}},
       {"han", {"h", "an"}},
       {"hang", {"h", "ang"}},
       {"hao", {"h", "ao"}},
       {"he", {"h", "e"}},
       {"hei", {"h", "ei"}},
       {"hen", {"h", "en"}},
       {"heng", {"h", "eng"}},
       {"hong", {"h", "ong"}},
       {"hou", {"h", "ou"}},
       {"hu", {"h", "u"}},
       {"hua", {"h", "ua"}},
       {"huai", {"h", "uai"}},
       {"huan", {"h", "uan"}},
       {"huang", {"h", "uang"}},
       {"hui", {"h", "uei"}},
       {"hun", {"h", "uen"}},
       {"huo", {"h", "uo"}},
       {"ji", {"j", "i"}},
       {"jia", {"j", "ia"}},
       {"jian", {"j", "ian"}},
       {"jiang", {"j", "iang"}},
       {"jiao", {"j", "iao"}},
       {"jie", {"j", "ie"}},
       {"jin", {"j", "in"}},
       {"jing", {"j", "ing"}},
       {"jiong", {"j", "iong"}},
       {"jiu", {"j", "iou"}},
       {"ju", {"j", "v"}},
       {"juan", {"j", "van"}},
       {"jue", {"j", "ve"}},
       {"jun", {"j", "vn"}},
       {"ka", {"k", "a"}},
       {"kai", {"k", "ai"}},
       {"kan", {"k", "an"}},
       {"kang", {"k", "ang"}},
       {"kao", {"k", "ao"}},
       {"ke", {"k", "e"}},
       {"kei", {"k", "ei"}},
       {"ken", {"k", "en"}},
       {"keng", {"k", "eng"}},
       {"kong", {"k", "ong"}},
       {"kou", {"k", "ou"}},
       {"ku", {"k", "u"}},
       {"kua", {"k", "ua"}},
       {"kuai", {"k", "uai"}},
       {"kuan", {"k", "uan"}},
       {"kuang", {"k", "uang"}},
       {"kui", {"k", "uei"}},
       {"kun", {"k", "uen"}},
       {"kuo", {"k", "uo"}},
       {"la", {"l", "a"}},
       {"lai", {"l", "ai"}},
       {"lan", {"l", "an"}},
       {"lang", {"l", "ang"}},
       {"lao", {"l", "ao"}},
       {"le", {"l", "e"}},
       {"lei", {"l", "ei"}},
       {"leng", {"l", "eng"}},
       {"li", {"l", "i"}},
       {"lia", {"l", "ia"}},
       {"lian", {"l", "ian"}},
       {"liang", {"l", "iang"}},
       {"liao", {"l", "iao"}},
       {"lie", {"l", "ie"}},
       {"lin", {"l", "in"}},
       {"ling", {"l", "ing"}},
       {"liu", {"l", "iou"}},
       {"lo", {"l", "o"}},
       {"long", {"l", "ong"}},
       {"lou", {"l", "ou"}},
       {"lu", {"l", "u"}},
       {"lv", {"l", "v"}},
       {"luan", {"l", "uan"}},
       {"lve", {"l", "ve"}},
       {"lue", {"l", "ve"}},
       {"lun", {"l", "uen"}},
       {"luo", {"l", "uo"}},
       {"ma", {"m", "a"}},
       {"mai", {"m", "ai"}},
       {"man", {"m", "an"}},
       {"mang", {"m", "ang"}},
       {"mao", {"m", "ao"}},
       {"me", {"m", "e"}},
       {"mei", {"m", "ei"}},
       {"men", {"m", "en"}},
       {"meng", {"m", "eng"}},
       {"mi", {"m", "i"}},
       {"mian", {"m", "ian"}},
       {"miao", {"m", "iao"}},
       {"mie", {"m", "ie"}},
       {"min", {"m", "in"}},
       {"ming", {"m", "ing"}},
       {"miu", {"m", "iou"}},
       {"mo", {"m", "o"}},
       {"mou", {"m", "ou"}},
       {"mu", {"m", "u"}},
       {"na", {"n", "a"}},
       {"nai", {"n", "ai"}},
       {"nan", {"n", "an"}},
       {"nang", {"n", "ang"}},
       {"nao", {"n", "ao"}},
       {"ne", {"n", "e"}},
       {"nei", {"n", "ei"}},
       {"nen", {"n", "en"}},
       {"neng", {"n", "eng"}},
       {"ni", {"n", "i"}},
       {"nia", {"n", "ia"}},
       {"nian", {"n", "ian"}},
       {"niang", {"n", "iang"}},
       {"niao", {"n", "iao"}},
       {"nie", {"n", "ie"}},
       {"nin", {"n", "in"}},
       {"ning", {"n", "ing"}},
       {"niu", {"n", "iou"}},
       {"nong", {"n", "ong"}},
       {"nou", {"n", "ou"}},
       {"nu", {"n", "u"}},
       {"nv", {"n", "v"}},
       {"nuan", {"n", "uan"}},
       {"nve", {"n", "ve"}},
       {"nue", {"n", "ve"}},
       {"nuo", {"n", "uo"}},
       {"o", {"^", "o"}},
       {"ou", {"^", "ou"}},
       {"pa", {"p", "a"}},
       {"pai", {"p", "ai"}},
       {"pan", {"p", "an"}},
       {"pang", {"p", "ang"}},
       {"pao", {"p", "ao"}},
       {"pe", {"p", "e"}},
       {"pei", {"p", "ei"}},
       {"pen", {"p", "en"}},
       {"peng", {"p", "eng"}},
       {"pi", {"p", "i"}},
       {"pian", {"p", "ian"}},
       {"piao", {"p", "iao"}},
       {"pie", {"p", "ie"}},
       {"pin", {"p", "in"}},
       {"ping", {"p", "ing"}},
       {"po", {"p", "o"}},
       {"pou", {"p", "ou"}},
       {"pu", {"p", "u"}},
       {"qi", {"q", "i"}},
       {"qia", {"q", "ia"}},
       {"qian", {"q", "ian"}},
       {"qiang", {"q", "iang"}},
       {"qiao", {"q", "iao"}},
       {"qie", {"q", "ie"}},
       {"qin", {"q", "in"}},
       {"qing", {"q", "ing"}},
       {"qiong", {"q", "iong"}},
       {"qiu", {"q", "iou"}},
       {"qu", {"q", "v"}},
       {"quan", {"q", "van"}},
       {"que", {"q", "ve"}},
       {"qun", {"q", "vn"}},
       {"ran", {"r", "an"}},
       {"rang", {"r", "ang"}},
       {"rao", {"r", "ao"}},
       {"re", {"r", "e"}},
       {"ren", {"r", "en"}},
       {"reng", {"r", "eng"}},
       {"ri", {"r", "iii"}},
       {"rong", {"r", "ong"}},
       {"rou", {"r", "ou"}},
       {"ru", {"r", "u"}},
       {"rua", {"r", "ua"}},
       {"ruan", {"r", "uan"}},
       {"rui", {"r", "uei"}},
       {"run", {"r", "uen"}},
       {"ruo", {"r", "uo"}},
       {"sa", {"s", "a"}},
       {"sai", {"s", "ai"}},
       {"san", {"s", "an"}},
       {"sang", {"s", "ang"}},
       {"sao", {"s", "ao"}},
       {"se", {"s", "e"}},
       {"sen", {"s", "en"}},
       {"seng", {"s", "eng"}},
       {"sha", {"sh", "a"}},
       {"shai", {"sh", "ai"}},
       {"shan", {"sh", "an"}},
       {"shang", {"sh", "ang"}},
       {"shao", {"sh", "ao"}},
       {"she", {"sh", "e"}},
       {"shei", {"sh", "ei"}},
       {"shen", {"sh", "en"}},
       {"sheng", {"sh", "eng"}},
       {"shi", {"sh", "iii"}},
       {"shou", {"sh", "ou"}},
       {"shu", {"sh", "u"}},
       {"shua", {"sh", "ua"}},
       {"shuai", {"sh", "uai"}},
       {"shuan", {"sh", "uan"}},
       {"shuang", {"sh", "uang"}},
       {"shui", {"sh", "uei"}},
       {"shun", {"sh", "uen"}},
       {"shuo", {"sh", "uo"}},
       {"si", {"s", "ii"}},
       {"song", {"s", "ong"}},
       {"sou", {"s", "ou"}},
       {"su", {"s", "u"}},
       {"suan", {"s", "uan"}},
       {"sui", {"s", "uei"}},
       {"sun", {"s", "uen"}},
       {"suo", {"s", "uo"}},
       {"ta", {"t", "a"}},
       {"tai", {"t", "ai"}},
       {"tan", {"t", "an"}},
       {"tang", {"t", "ang"}},
       {"tao", {"t", "ao"}},
       {"te", {"t", "e"}},
       {"tei", {"t", "ei"}},
       {"teng", {"t", "eng"}},
       {"ti", {"t", "i"}},
       {"tian", {"t", "ian"}},
       {"tiao", {"t", "iao"}},
       {"tie", {"t", "ie"}},
       {"ting", {"t", "ing"}},
       {"tong", {"t", "ong"}},
       {"tou", {"t", "ou"}},
       {"tu", {"t", "u"}},
       {"tuan", {"t", "uan"}},
       {"tui", {"t", "uei"}},
       {"tun", {"t", "uen"}},
       {"tuo", {"t", "uo"}},
       {"wa", {"^", "ua"}},
       {"wai", {"^", "uai"}},
       {"wan", {"^", "uan"}},
       {"wang", {"^", "uang"}},
       {"wei", {"^", "uei"}},
       {"wen", {"^", "uen"}},
       {"weng", {"^", "ueng"}},
       {"wo", {"^", "uo"}},
       {"wu", {"^", "u"}},
       {"xi", {"x", "i"}},
       {"xia", {"x", "ia"}},
       {"xian", {"x", "ian"}},
       {"xiang", {"x", "iang"}},
       {"xiao", {"x", "iao"}},
       {"xie", {"x", "ie"}},
       {"xin", {"x", "in"}},
       {"xing", {"x", "ing"}},
       {"xiong", {"x", "iong"}},
       {"xiu", {"x", "iou"}},
       {"xu", {"x", "v"}},
       {"xuan", {"x", "van"}},
       {"xue", {"x", "ve"}},
       {"xun", {"x", "vn"}},
       {"ya", {"^", "ia"}},
       {"yan", {"^", "ian"}},
       {"yang", {"^", "iang"}},
       {"yao", {"^", "iao"}},
       {"ye", {"^", "ie"}},
       {"yi", {"^", "i"}},
       {"yin", {"^", "in"}},
       {"ying", {"^", "ing"}},
       {"yo", {"^", "iou"}},
       {"yong", {"^", "iong"}},
       {"you", {"^", "iou"}},
       {"yu", {"^", "v"}},
       {"yuan", {"^", "van"}},
       {"yue", {"^", "ve"}},
       {"yun", {"^", "vn"}},
       {"za", {"z", "a"}},
       {"zai", {"z", "ai"}},
       {"zan", {"z", "an"}},
       {"zang", {"z", "ang"}},
       {"zao", {"z", "ao"}},
       {"ze", {"z", "e"}},
       {"zei", {"z", "ei"}},
       {"zen", {"z", "en"}},
       {"zeng", {"z", "eng"}},
       {"zha", {"zh", "a"}},
       {"zhai", {"zh", "ai"}},
       {"zhan", {"zh", "an"}},
       {"zhang", {"zh", "ang"}},
       {"zhao", {"zh", "ao"}},
       {"zhe", {"zh", "e"}},
       {"zhei", {"zh", "ei"}},
       {"zhen", {"zh", "en"}},
       {"zheng", {"zh", "eng"}},
       {"zhi", {"zh", "iii"}},
       {"zhong", {"zh", "ong"}},
       {"zhou", {"zh", "ou"}},
       {"zhu", {"zh", "u"}},
       {"zhua", {"zh", "ua"}},
       {"zhuai", {"zh", "uai"}},
       {"zhuan", {"zh", "uan"}},
       {"zhuang", {"zh", "uang"}},
       {"zhui", {"zh", "uei"}},
       {"zhun", {"zh", "uen"}},
       {"zhuo", {"zh", "uo"}},
       {"zi", {"z", "ii"}},
       {"zong", {"z", "ong"}},
       {"zou", {"z", "ou"}},
       {"zu", {"z", "u"}},
       {"zuan", {"z", "uan"}},
       {"zui", {"z", "uei"}},
       {"zun", {"z", "uen"}},
       {"zuo", {"z", "uo"}}
    };
}
